name: Develop PR Check
on:
  pull_request:
    branches:
      - develop

jobs:
  build :
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo Directory
      uses: actions/checkout@v2
    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.15.0'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Install Dependencies
      run: pnpm install --prefer-offline --no-frozen-lockfile
  unittest :
    name: Run UnitTest
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to Repo Directory
      uses: actions/checkout@v2
    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.15.0'
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Get Cache Node Module
      run: pnpm install --prefer-offline --no-frozen-lockfile
    - name: run unit test:unit
      run: pnpm run test:unit
    - name: upload Unit Test report
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test report
        path: ${{ github.workspace }}/mochawesome-report
        retention-days: 1
    - name: Coverage monitor
      uses: slavcodev/coverage-monitor-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverage_path: "coverage/clover.xml"
        threshold_alert: 10
        threshold_warning: 50
        comment_context: 'Unit Test Report'
    - name: upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage report
        path: ${{ github.workspace }}/coverage
        retention-days: 1